# Generated by Django 2.2.4 on 2019-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='work_interfere',
            field=models.CharField(choices=[('often', 'Often'), ('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('never', 'Never')], default='', max_length=25),
        ),
    ]
