# Generated by Django 2.2.4 on 2019-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20190831_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Details'},
        ),
        migrations.AddField(
            model_name='details',
            name='treatment_required',
            field=models.CharField(default='', max_length=5),
        ),
    ]
