# Generated by Django 2.2.4 on 2019-08-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20190831_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='treatment',
        ),
    ]
