# Generated by Django 2.2.4 on 2019-09-01 00:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_remove_details_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 1, 0, 51, 9, 770915, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
