# Generated by Django 2.2.4 on 2019-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20190901_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='family_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='obs_consequence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='remote_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='self_employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='tech_company',
            field=models.BooleanField(default=False),
        ),
    ]
