# Generated by Django 2.2.4 on 2019-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_auto_20190902_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='family_history',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='obs_consequence',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='remote_work',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='self_employment',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='tech_company',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
    ]
